name: roderfile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs_on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.18.x, 1.19.x]
  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up Go
    uses: actions/setup-go@v2
    with:
      go-version: ${{ matrix.go-version }}

  - name: Build
    run: go build -v ./...

  - name: Test
    run: go test -v ./...
    
